language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - pypy
matrix:
  include:
    - python: 2.6
      dist: trusty
install:
  - pip install tox
script:
  - tox -e py
