version: build-{build}-{branch}

environment:
  matrix:
    # http://www.appveyor.com/docs/installed-software#python lists available
    # versions
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

init:
  - "echo %PYTHON%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - python -m pip install -U pip
  - python -m pip install -U setuptools
  - python -m pip install -U wheel virtualenv tox

build: false

test_script:
  - tox -v -e py
